from langchain_core.tools import tool
from pydantic import BaseModel, Field
from typing import Optional
from app.services.processor import StickerProcessor
import os

# --- Input Schemas ---

class RemoveBackgroundInput(BaseModel):
    input_path: str = Field(description="The full path or filename of the image to process.")
    output_path: Optional[str] = Field(default=None, description="The path where the background-removed image should be saved. If not provided, it will save to data/output/nobg_[input_filename].png")
    erosion_size: int = Field(default=1, description="Size for edge erosion to remove halos. 0-3 is typical.")
    island_size: int = Field(default=100, description="Minimum area for a connected component to be kept. Helps remove noise/specks.")

class ResizeImageInput(BaseModel):
    input_path: str = Field(description="The full path or filename of the image to resize.")
    output_path: Optional[str] = Field(default=None, description="The path where the resized image should be saved.")
    target_width: int = Field(default=370, description="Target width in pixels.")
    target_height: int = Field(default=320, description="Target height in pixels.")

class GenerateImageInput(BaseModel):
    prompt: str = Field(description="The text prompt to generate an image from.")
    output_filename: str = Field(description="The filename to save the generated image as (e.g., 'generated_char.jpg').")

class CheckBackgroundInput(BaseModel):
    input_path: str = Field(description="The path to the image to check for background/transparency.")

# --- Processor Singleton ---

_processor = None

def get_processor():
    global _processor
    if _processor is None:
        _processor = StickerProcessor()
    return _processor

# --- Tool Definitions ---

@tool("generate_image", args_schema=GenerateImageInput, return_direct=False)
def generate_image_tool(prompt: str, output_filename: str) -> str:
    """
    Generates an image from a text prompt using Google Gemini Imagen API or Banana.dev.
    
    Use this tool FIRST when creating a sticker to generate the base image.
    The prompt should describe the visual appearance of the sticker character or object.
    
    Args:
        prompt: Detailed description of the image to generate
        output_filename: Name for the saved file (e.g., 'cat_sticker.jpg')
    
    Returns:
        Success message with file path or error message
    """
    output_path = os.path.join("data", "input", output_filename)
    processor = get_processor()
    try:
        final_path = processor.generate_image(prompt, output_path)
        return f"Image generated successfully and saved at: {final_path}"
    except Exception as e:
        return f"Error generating image: {str(e)}"

@tool("check_image_background", args_schema=CheckBackgroundInput, return_direct=False)
def check_background_tool(input_path: str) -> str:
    """
    Checks if an image has a transparent background or needs background removal.
    
    Use this tool AFTER generating an image to determine if background removal is needed.
    Returns 'transparent' if the image already has transparency, or 'has_background' if it needs processing.
    
    Args:
        input_path: Path to the image file to check
    
    Returns:
        Either 'transparent' or 'has_background'
    """
    if not os.path.isabs(input_path) and not input_path.startswith("data/"):
        input_path = os.path.join("data", "input", input_path)
        
    processor = get_processor()
    try:
        if processor.has_transparency(input_path):, return_direct=False)
def remove_background_tool(
    input_path: str,
    output_path: Optional[str] = None,
    erosion_size: int = 1,
    island_size: int = 100
) -> str:
    """
    Removes the background from an image using AI segmentation, creating a transparent PNG.
    
    Use this tool when an image has a background that needs to be removed for sticker creation.
    This uses the RMBG-1.4 model for professional-grade background removal with edge cleaning.
    
    Args:
        input_path: Path to the image with background
        output_path: Optional output path (auto-generated if not provided)
        erosion_size: Edge erosion to remove halos (0-3 recommended, default 1)
        island_size: Minimum pixel area to keep (removes noise, default 100)
    
    Returns:
        Success message with output file path or error message
    output_path: Optional[str] = None,
    erosion_size: int = 1,
    island_size: int = 100
) -> str:
    """
    Removes the background from an image. Use this when an image (like one generated by an AI) 
    has an unwanted background and needs to be converted into a transparent PNG.
    """
    # Normalize paths
    if not os.path.isabs(input_path) and not input_path.startswith("data/"):
        input_path = os.path.join("data", "input", input_path)
    , return_direct=False)
def resize_image_tool(
    input_path: str,
    output_path: Optional[str] = None,
    target_width: int = 370,
    target_height: int = 320
) -> str:
    """
    Resizes an image to standard sticker dimensions while maintaining aspect ratio and quality.
    
    Use this tool as the FINAL STEP to format the sticker to standard dimensions (370x320px).
    The image is centered on a transparent canvas with high-quality LANCZOS resampling.
    
    Args:
        input_path: Path to the image to resize (usually the background-removed version)
        output_path: Optional output path (auto-generated if not provided)
        target_width: Target width in pixels (default 370)
        target_height: Target height in pixels (default 320)
    
    Returns:
        Success message with final sticker path or error message
            output_path=output_path,
            erosion_size=erosion_size,
            island_size=island_size
        )
        return f"Background removed successfully. File saved at: {final_path}"
    except Exception as e:
        return f"Error removing background: {str(e)}"

@tool("resize_for_sticker", args_schema=ResizeImageInput)
def resize_image_tool(
    input_path: str,
    output_path: Optional[str] = None,
    target_width: int = 370,
    target_height: int = 320
) -> str:
    """
    Resizes an image to specific dimensions (default 370x320) while maintaining aspect ratio.
    The image will be centered on a transparent canvas. Useful for final sticker formatting.
    """
    if not os.path.isabs(input_path) and not input_path.startswith("data/"):
        input_path = os.path.join("data", "output", input_path)

    if output_path is None:
        filename = os.path.basename(input_path)
        name, _ = os.path.splitext(filename)
        output_path = os.path.join("data", "output", f"{name}_resized.png")

    processor = get_processor()
    try:
        final_path = processor.resize_image(
            input_path=input_path,
            output_path=output_path,
            target_size=(target_width, target_height)
        )
        return f"Image resized successfully. File saved at: {final_path}"
    except Exception as e:
        return f"Error resizing image: {str(e)}"